apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: demo-appliaction
  name: demo-appliaction
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: demo-appliaction
  template:
    metadata:
      labels:
        app.kubernetes.io/name: demo-appliaction
    spec:
      containers:
        - image: bejenar/demo:<tag_version>
          name: demo-appliaction
          ports:
            - containerPort: 8080
          env:
            - name: FOO_BAR
              value: "This is string from env vars"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password